server:
  port: 8080

spring:
  datasource:
   url: jdbc:oracle:thin:@localhost:1521:xe
   password: ezpay123
   username: system
   driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    generate-ddl: false
    show-sql: true 
    database-platform: org.hibernate.dialect.OracleDialect